add matrixTransform & init DOMMatrix
M-CreativeLab/jsar-dom pull request #12
Opened 2024-03-14 09:51 UTC by neverbiasu

I encapsulated the `matrixTransform` method in `DOMPoint` and also provided a basic implementation for `DOMMatrix`. 

This involved defining how `DOMMatrix` initializes and how it interacts with `DOMPoint` through the `matrixTransform` method to apply transformations.

2024-03-14 13:18 UTC, yorkie requested changes
PR 的描述格式也需要修改，当前的不容易阅读。

2024-03-14 13:18 UTC, yorkie commented on src/living/geometry/DOMMatrixReadOnly.ts
> +        }
请按照规范中实现：https://www.w3.org/TR/geometry-1/#dom-dommatrixreadonly-translate。
规范中这里是调用 translateSelf() 来实现的。

2024-03-14 13:18 UTC, yorkie commented on src/living/geometry/DOMMatrixReadOnly.ts
> +        // Implement the rotateAxisAngleSelf method here.
同上

2024-03-14 13:18 UTC, yorkie commented on src/living/geometry/DOMMatrixReadOnly.ts
> +        // Implement the rotateFromVectorSelf method here.
同上

2024-03-14 13:18 UTC, yorkie commented on src/living/geometry/DOMPoint.test.ts
> +  function getMatrixTransform(matrix: DOMMatrix, point: DOMPoint) {
这里可以添加一行注释，标记一下从 wpt 哪个版本的哪个文件拷贝的测试用例

2024-03-14 13:18 UTC, yorkie commented on src/living/geometry/DOMPoint.test.ts
> +    console.log("exp.x: ", exp.x);
在测试文件中尽量不要使用 console，并且需要注意格式

2024-03-14 13:18 UTC, yorkie commented on src/living/geometry/DOMPoint.test.ts
> +    else {
```suggestion
   } else {
```

2024-03-14 13:18 UTC, yorkie commented on src/living/geometry/DOMPoint.test.ts
> +
多余的空行

2024-03-14 13:18 UTC, yorkie commented on src/living/geometry/DOMPoint.ts
>  export const GET_UPDATER_SYMBOL = Symbol('__getUpdater__');
Symbol 可以和这个命名风格保持一致

2024-03-14 13:18 UTC, yorkie commented on src/living/geometry/DOMPoint.ts
> +      console.log(midmatrix);
多余的日志

2024-03-14 13:18 UTC, yorkie commented on src/living/geometry/DOMPoint.ts
> +      glMatrix.vec2.transformMat4(pointVector,pointVector,transformMatrix);
注意格式

2024-03-14 13:18 UTC, yorkie commented on src/living/geometry/DOMPoint.ts
> +      const midmatrix = new DOMMatrix([matrix.a, matrix.b, matrix.c,
关于 `midmatrix` 的命名：

- 使用驼峰命名 => `midMatrix`
- 这个命名具体代表什么含义呢

2024-03-14 13:18 UTC, yorkie commented on src/living/geometry/DOMPoint.ts
> +      // 2D
这个注释没有太大的意义，上面的 `matrix.is2D` 足够表达了。

2024-03-14 13:18 UTC, yorkie commented on src/living/geometry/DOMPoint.ts
> +      const midmatrix = new DOMMatrix([matrix.a, matrix.b, matrix.c,
2D 矩阵的分组是 `ab`, `cd`, `ef`

2024-03-14 13:18 UTC, yorkie commented on src/living/geometry/DOMPoint.ts
> +    }
需要按照规范中说明的实现来，比如在规范中，并没有在最外层判断 2D or 3D，而是在创建 matrix 时，之后的逻辑是通用的逻辑了：https://www.w3.org/TR/geometry-1/#transforming-a-point-with-a-matrix。

2024-03-14 13:18 UTC, yorkie commented on src/living/geometry/DOMPoint.ts
> +    }
> Set pointVector to pointVector [post-multiplied](https://www.w3.org/TR/geometry-1/#post-multiply) by matrix.

在实现这个函数之前，需要使用 gl-matrix 实现 post-multiply 的功能，关于 `post-multiply`/`pre-multiply`/`multiply`，都定义在 https://www.w3.org/TR/geometry-1/#DOMMatrix。

2024-03-14 13:55 UTC, neverbiasu commented
收到🫡

2024-03-14 14:53 UTC, neverbiasu commented on src/living/geometry/DOMPoint.ts
> +      // 2D
好的

2024-03-14 15:12 UTC, neverbiasu commented on src/living/geometry/DOMPoint.ts
> +    }
好的师傅，徒儿明白了

2024-03-14 15:16 UTC, neverbiasu commented on src/living/geometry/DOMMatrix.ts
> +        return this._internalData[2];
明白了

2024-03-14 15:18 UTC, neverbiasu commented on src/living/geometry/DOMMatrix.ts
> +        return this._internalData[0];
是的

2024-03-14 15:21 UTC, neverbiasu commented on src/living/geometry/DOMMatrix.test.ts
> +});
学到了

> 源码最后一行需要留一个空行。

2024-03-14 15:39 UTC, yorkie commented on src/living/geometry/DOMPoint.ts
> +      const midmatrix = new DOMMatrix([matrix.a, matrix.b, matrix.c,
那命名应该叫 immediateMatrix 或者 tmpMatrix 更好哦

2024-03-15 00:58 UTC, neverbiasu commented on src/living/geometry/DOMPoint.ts
> +      const midmatrix = new DOMMatrix([matrix.a, matrix.b, matrix.c,
好的

2024-03-15 02:15 UTC, neverbiasu commented on src/living/geometry/DOMMatrix.ts
> +        return this._internalData[0];
已更换成`matrixElement`

2024-03-15 02:24 UTC, neverbiasu commented on src/living/geometry/DOMMatrixReadOnly.ts
> +export const kReadInternalData = Symbol('_ReadInternalSymbol');
已更换成`kGetMatrixElements`

2024-03-15 02:53 UTC, neverbiasu commented on src/living/geometry/DOMMatrixReadOnly.ts
> +        }
不清楚constructor应该return什么，文档说的是要返回matrix

> Return the result of invoking [create a 3d matrix](https://www.w3.org/TR/geometry-1/#create-a-3d-matrix) of type [DOMMatrixReadOnly](https://www.w3.org/TR/geometry-1/#dommatrixreadonly) or [DOMMatrix](https://www.w3.org/TR/geometry-1/#dommatrix) as appropriate, with the sequence init.

，那我们是返回DOMMatrix吗，有点昏

2024-03-15 03:15 UTC, neverbiasu commented on src/living/geometry/DOMPoint.ts
>  export const GET_UPDATER_SYMBOL = Symbol('__getUpdater__');
好的，已修改成`kGetMatrixElements`

2024-03-15 03:20 UTC, yorkie commented on src/living/geometry/DOMMatrix.ts
> +        return this._internalData[0];
换成 matrixElements 好一些，因为是数组

2024-03-15 03:21 UTC, yorkie commented on src/living/geometry/DOMMatrixReadOnly.ts
> +        }
constructor 返回空就行

2024-04-16 06:36 UTC, yorkie commented on src/living/geometry/DOMMatrix.ts
> +export default class DOMMatrixImpl extends DOMMatrixReadOnlyImpl implements DOMMatrix {
在 import 后最好有一个空格

2024-04-16 06:45 UTC, neverbiasu commented on src/living/geometry/DOMMatrix.ts
> +export default class DOMMatrixImpl extends DOMMatrixReadOnlyImpl implements DOMMatrix {
好的

2024-04-16 09:32 UTC, yorkie commented on src/living/geometry/DOMMatrix.test.ts
> +   });
对齐问题

2024-04-16 09:33 UTC, yorkie commented on src/living/geometry/DOMMatrix.test.ts
> +    const matrix = new DOMMatrixImpl([1,1,1,1, 1,1,1,1, 1,1,1,1, 1,1,1,1]);
```suggestion
    const matrix = new DOMMatrixImpl([
      1, 1, 1, 1,
      1, 1, 1, 1,
      1, 1, 1, 1,
      1, 1, 1, 1
    ]);
```
可以这么写，在数组字面量的定义，逗号后面需要空格。

2024-04-16 09:35 UTC, yorkie commented on src/living/geometry/DOMMatrix.ts
> +    throw new Error("Method not implemented.");
```suggestion
    throw new Error('Method not implemented.');
```

2024-04-16 09:35 UTC, yorkie commented on src/living/geometry/DOMMatrix.ts
> +    throw new Error("Method not implemented.");
同上

2024-04-16 09:36 UTC, yorkie commented on src/living/geometry/DOMMatrix.ts
> +    const scalationMatrix = new DOMMatrixImpl([scaleX ?? 1,0,0,0,  0,scaleY ?? scaleX ?? 1,0,0,  0,0, scaleZ ?? 1,0,  0,0,0,1]);
空格

2024-04-16 09:38 UTC, yorkie commented on src/living/geometry/DOMMatrixReadOnly.ts
> +export const Get_Matrix_Elements = Symbol('_ReadInternalSymbol');
https://github.com/M-CreativeLab/jsar-dom/blob/317a18495fa931ce3df5f08ba7af8605be2bf63a/src/symbols.ts#L2
参考这里的 Symbol 命名

2024-04-16 09:39 UTC, yorkie commented on src/living/geometry/DOMMatrixReadOnly.ts
> +    // init is omitted
这一行注释是什么意思？

2024-04-16 09:40 UTC, yorkie commented on src/living/geometry/DOMMatrixReadOnly.ts
> +    throw new TypeError("Invalid type for matrix initialization.");
```suggestion
    throw new TypeError('Invalid type for matrix initialization.');
```

2024-04-16 09:41 UTC, yorkie commented on src/living/geometry/DOMMatrixReadOnly.ts
> +    const tmpMatrix = new DOMMatrixImpl(Array.from(this._matrixElements));
这里叫 `tmpMatrix` 不太合适，因为最终这个对象被返回了，它并不是“临时的”。

2024-04-16 09:41 UTC, yorkie commented on src/living/geometry/DOMMatrixReadOnly.ts
> +    const tmpMatrix = new DOMMatrixImpl(Array.from(this._matrixElements));
同理

2024-04-16 09:41 UTC, yorkie commented on src/living/geometry/DOMMatrixReadOnly.ts
> +    throw new Error("Method not implemented.")
```suggestion
    throw new Error('Method not implemented.')
```

2024-04-16 09:42 UTC, yorkie commented on src/living/geometry/DOMMatrixReadOnly.ts
> +  };
缩进不正确

2024-04-16 09:43 UTC, yorkie commented on src/living/geometry/DOMPoint.test.ts
>  describe('DOMPoint', () => {
这里需要空一行

2024-04-16 09:43 UTC, yorkie commented on src/living/geometry/DOMPoint.ts
>  export const GET_UPDATER_SYMBOL = Symbol('__getUpdater__');
同上

2024-04-16 09:43 UTC, yorkie commented on src/living/geometry/DOMPoint.ts
> +    if(matrix.is2D && this.z === 0 && this.w === 1) {
```suggestion
    if (matrix.is2D && this.z === 0 && this.w === 1) {
```

2024-04-16 09:45 UTC, yorkie commented on src/living/geometry/MatrixFunction.ts
> +import { Get_Matrix_Elements } from './DOMMatrixReadOnly';
living/geometry 下面都需要标准接口，而且文件是大写驼峰表示它是一个类，这里建议移到 utils 或者 helpers 中

2024-04-16 09:45 UTC, yorkie commented on src/living/geometry/MatrixFunction.ts
> +export function post_multiply(self: DOMMatrix, other: DOMMatrix): DOMMatrix {
```suggestion
export function postMultiply(self: DOMMatrix, other: DOMMatrix): DOMMatrix { 
```

2024-04-16 09:45 UTC, yorkie commented on src/living/geometry/MatrixFunction.ts
> +export function pre_multiply(other: DOMMatrix, self: DOMMatrix): DOMMatrix {
```suggestion
export function preMultiply(other: DOMMatrix, self: DOMMatrix): DOMMatrix { 
```
同上，函数命名需要使用驼峰命名规范。

2024-04-16 09:46 UTC, yorkie commented on src/living/geometry/MatrixFunction.ts
> +  for(let i = 0; i < 16; i = i + 1) {
```suggestion
  for (let i = 0; i < 16; i = i + 1) {
```

2024-04-16 09:46 UTC, yorkie commented on src/living/geometry/MatrixFunction.ts
> +  const resMatrix = new DOMMatrixImpl(resElements);
这里的 res 指的什么意思？

2024-04-16 10:09 UTC, neverbiasu commented on src/living/geometry/DOMMatrixReadOnly.ts
> +    // init is omitted
`If init is omitted`是init被省略了

2024-04-16 10:24 UTC, neverbiasu commented on src/living/geometry/MatrixFunction.ts
> +  const resMatrix = new DOMMatrixImpl(resElements);
result的意思

2024-04-18 06:07 UTC, yorkie commented on src/living/geometry/DOMMatrix.ts
> +    return new DOMMatrixImpl([array32[0], array32[1], array32[2], array32[3], array32[4], array32[5], array32[6], array32[7], array32[8], array32[9], array32[10], array32[11], array32[12], array32[13
这一行太长了

2024-04-18 06:10 UTC, yorkie commented on src/living/geometry/DOMMatrix.ts
> +    const resMatrix = postMultiply(this, otherObject);
这个 res 代表什么意思？

2024-04-18 06:14 UTC, yorkie commented on src/living/geometry/DOMMatrixReadOnly.ts
> +    // init is omitted
```suggestion
    // `init` is omitted
```

2024-04-18 06:27 UTC, yorkie requested changes

2024-04-18 06:27 UTC, yorkie commented on src/living/geometry/DOMMatrixReadOnly.ts
> +      this._matrixElements[14] = 0;
可以通过 `fill(0)` 来减少这些代码

2024-04-18 06:27 UTC, yorkie commented on src/living/geometry/DOMMatrixReadOnly.ts
> +      }
```suggestion
this._matrixElements.set(init)
```

2024-04-18 06:27 UTC, yorkie commented on src/living/geometry/DOMPoint.ts
> +import { Get_Matrix_Elements } from './DOMMatrixReadOnly'
```suggestion
import { Get_Matrix_Elements } from './DOMMatrixReadOnly';
```

2024-04-18 06:27 UTC, yorkie commented on package.json
> +    "gl-matrix": "^3.4.3",
这个依赖并没有被使用到

2024-04-18 07:23 UTC, yorkie commented on src/living/geometry/DOMPoint.ts
> +    const point = new DOMPointImpl(matrix[GET_MATRIX_ELEMENTS]()[0], matrix[GET_MATRIX_ELEMENTS]()[4], matrix[GET_MATRIX_ELEMENTS]()[8], matrix[GET_MATRIX_ELEMENTS]()[12]);
多次重复调用 `matrix[GET_MATRIX_ELEMENTS]()` 应该没有必要

2024-04-18 07:23 UTC, yorkie commented on src/living/geometry/DOMPoint.ts
> +    return pointMatrix;
没有必要的变量分配

2024-04-18 07:28 UTC, yorkie commented on src/living/helpers/matrix-functions.ts
> +      resElements[i] += Number(selfElements[k * 4 + i % 4]) * Number(otherElements[Math.floor(i / 4) * 4 + k]);
这里的 Number() 的目的是什么？`Float32Array` 里的元素应该只会是 number 类型，并不需要 Number 来转换。

2024-04-18 07:28 UTC, yorkie commented on src/living/helpers/matrix-functions.ts
> +  }
同理

2024-04-18 09:25 UTC, yorkie commented on src/living/geometry/DOMPoint.ts
> +      const transformed_y = this.x * matrix.m12 + this.y * matrix.m22 + matrix.m42;
```suggestion
      const transformedY = this.x * matrix.m12 + this.y * matrix.m22 + matrix.m42;
```

2024-04-18 09:39 UTC, yorkie approved these changes
LGTM

2024-04-18 09:41 UTC, merged