Let loadImplementations handle the situation of running inVM Modules
M-CreativeLab/jsar-dom pull request #14
Opened 2024-04-09 09:35 UTC by neverbiasu

2024-04-09 12:27 UTC, yorkie requested changes
另外，需要补充一个测试用例来验证这次的改动。

2024-04-10 03:21 UTC, yorkie commented on src/living/interfaces.ts
> +    isVMModules ? await import('./attributes/NamedNodeMap') : import('./attributes/NamedNodeMap'),
或者封装一个:

```ts
async importImplementations(names: string[], inParallel: boolean) {
  if (inParallel) {
    return Promise.all(names.map(() => import(name));
  } else {
    const impls = [];
    for (let name of names) {
      impls.push(await import(name));
    }
    return impls;
  }
}
```

然后使用如下：

```ts
importImplementations([
  './attributes/NamedNodeMap',
  ...
], inParallel).then((...) => {
  // ...
});
```

2024-04-10 08:37 UTC, yorkie commented on jest.setup.cjs
> +global.BABYLON = require('babylonjs');
添加一行注释说明为什么要 require babylonjs

2024-04-10 08:38 UTC, yorkie commented on src/living/interfaces.test.ts
> +    return 0;
`loadImplementations()` 后，需要使用对应的接口来使用 loaded 的模块，来确保加载逻辑正确。

2024-04-10 08:38 UTC, yorkie commented on src/living/interfaces.test.ts
> +    await expect(loadImplementations(isParallel)).resolves.toBeUndefined();
这里为什么要 await expect？

2024-04-10 08:39 UTC, yorkie commented on src/living/interfaces.ts
> +async function importImplementations(modulePaths: string[], isParallel: boolean) {
这里可以注释解释下为什么要添加这个函数以及 isParallel 参数的意义。

2024-04-10 08:40 UTC, yorkie commented on src/living/interfaces.ts
> +    return Promise.all(modulePaths.map((path) => import(path)));
`isParallel === false` 意味着是串行，是不是写反了？

2024-04-10 09:44 UTC, yorkie commented on src/living/interfaces.test.ts
注释要放到要说明的代码之前，另外这里的注释要说明为什么需要在测试环境下引入 babylonjs

2024-04-10 09:45 UTC, yorkie commented on src/living/interfaces.test.ts
> +    await expect(loadImplementations(isParallel)).resolves.toBeUndefined();
这里为什么需要检查 loadImplementations() 的返回值是否是 undefined 呢？
应该是调用之后能正常 import 对应的 DOM interface

2024-04-10 09:48 UTC, yorkie commented on src/living/interfaces.ts
> +async function importImplementations(modulePaths: string[], isParallel: boolean) {
这里需要解释 Node.js vm module 中不支持并行的动态导入（import）并附上相关的 issues，而不是解释这个函数本身。

2024-04-10 09:48 UTC, yorkie commented on src/living/interfaces.ts
> +    for (const path of modulePaths) {
```suggestion
    for (const specifier of moduleSpecifiers) {
```
与 Node.js 命名保持统一。

2024-04-10 09:50 UTC, yorkie commented on src/living/interfaces.ts
> +    ], isParallel).then(([
这一行对齐有问题，多了两个空格。

2024-04-10 09:50 UTC, yorkie commented on src/living/interfaces.ts
> +async function importImplementations(modulePaths: string[], isParallel: boolean) {
这个函数缺少返回值类型声明

2024-04-12 03:07 UTC, neverbiasu commented on src/living/interfaces.test.ts
> +    await expect(loadImplementations(isParallel)).resolves.toBeUndefined();
不太理解

> 调用之后能正常 import 对应的 DOM interface

是指用一下每个interface的功能来确认是否正常导入吗

2024-04-12 06:52 UTC, yorkie approved these changes
LGTM, Thanks for this contribution @neverbiasu

2024-04-12 06:58 UTC, merged