Interfaces
M-CreativeLab/jsar-dom pull request #15
Opened 2024-05-07 03:04 UTC by neverbiasu

wrote a genertate.js to generate interfaces.ts‘s code with babel, now the generate result put in interface.ts file.

2024-05-07 03:10 UTC, neverbiasu commented on src/living/interfaces.ts
> +// /**
Inexplicable comment

2024-05-07 03:10 UTC, neverbiasu commented on src/living/generate.js
> +// const getInterfaceWrapperCode = generate.default(getInterfaceWrapper).code;
remove the comments

2024-05-07 03:20 UTC, yorkie requested changes
可以再检查一下，没有看懂代码

2024-05-07 03:20 UTC, yorkie commented on src/living/interface.ts
> +import type NamedNodeMapImpl from './attributes/NamedNodeMap';
这个文件可以不用提交了

2024-05-07 03:25 UTC, neverbiasu commented on src/living/interface.ts
> +import type NamedNodeMapImpl from './attributes/NamedNodeMap';
ok

2024-05-08 05:59 UTC, neverbiasu commented on src/living/generate.js
> +const comments = `
move the comments into this file

2024-05-08 05:59 UTC, neverbiasu commented on src/living/generate.js
> +  // TODO: help me to fullfill the other interfaces
same

2024-05-09 05:23 UTC, neverbiasu commented on src/living/helpers/generate.js
> +const buildParallelImports = template.default(`
用`defaultTemplate`

2024-05-09 05:48 UTC, neverbiasu reviewed
good

2024-05-09 07:19 UTC, neverbiasu reviewed
- [x] abstract options of template
- [x] unify the placeholder
- [x] delete the useless files

2024-05-09 10:57 UTC, yorkie requested changes

2024-05-09 10:57 UTC, yorkie commented on package.json
> +    "generate-interfaces": "node ./tools/generate.js"
```suggestion
    "generate-dom-interfaces": "node ./tools/generate-dom-interfaces.js"
```

2024-05-09 10:57 UTC, yorkie commented on tools/generate.js
> +let defaultTemplate = template.smart({
```suggestion
const defaultTemplate = template.smart({
```

2024-05-09 10:57 UTC, yorkie commented on tools/generate.js
> +  if (arg.ISDEFAULT) {
```suggestion
  if (arg.IS_DEFAULT) {
```

2024-05-09 10:57 UTC, yorkie commented on tools/generate.js
> +    IFSTATEMENT
```suggestion
    IF_STATEMENT
```

2024-05-09 10:57 UTC, yorkie commented on tools/generate.js
> +      IMPLEMENTEDINTERFACES
```suggestion
      IMPLEMENTED_INTERFACES
```

2024-05-09 10:57 UTC, yorkie commented on tools/generate.js
> +  EXPORTFUNCTION
Ditto

2024-05-09 10:57 UTC, yorkie commented on tools/generate.js
> +const __dirname = 'src/living/';
`__dirname` is an existed variable in a Node.js commonjs module, could you please change the name?

2024-05-09 11:08 UTC, yorkie commented on tools/generate-dom-interfaces.js
> + * It is used to load all the implementations of the interfaces asynchronously.
```suggestion
 * It is used to load all the implementations of the interfaces asynchronously to avoid the circular dependeny
```

2024-05-09 11:09 UTC, yorkie commented on tools/generate-dom-interfaces.js
> + * project directory structure. To address this issue, we use dynamic imports() to load type
```suggestion
 * project directory structure. To address this issue, we use dynamic `imports()` to load type 
```

2024-05-09 11:09 UTC, yorkie commented on tools/generate-dom-interfaces.js
> + * instances asynchronously. We also provide a synchronous function, getInterfaceWrapper, to ensure
```suggestion
 * instances asynchronously. We also provide a function, getInterfaceWrapper, to ensure 
```

2024-05-09 11:17 UTC, yorkie commented on tools/generate-dom-interfaces.js
> +const buildModule = defaultTemplate(`
```suggestion
const buildModulesAssignment = defaultTemplate(`
```

2024-05-09 11:18 UTC, yorkie commented on tools/generate-dom-interfaces.js
> +  IS_PARALLEL: t.identifier('isParallel'),
This is unnecessary to be placeholder

2024-05-09 11:19 UTC, yorkie commented on tools/generate-dom-interfaces.js
> +const buildIfStatement = defaultTemplate(`
```suggestion
const buildModulesAssignment = defaultTemplate(`
```

2024-05-10 04:28 UTC, neverbiasu commented on tools/generate-dom-interfaces.js
> +    PARALLEL_MODULE
```suggestion
    PARALLEL_MODULES
```

2024-05-10 04:28 UTC, neverbiasu commented on tools/generate-dom-interfaces.js
> +    SEQUENTIAL_MODULE
```suggestion
    SEQUENTIAL_MODULES
```

2024-05-10 04:30 UTC, neverbiasu commented on tools/generate-dom-interfaces.js
> +  EXPORT_FUNCTION
```suggestion
  EXPORT_GET_INTERFACE_WRAPPER
```

2024-05-10 04:59 UTC, yorkie commented on tools/generate-dom-interfaces.js
> + * @param running parallel or not
Unnecessary param description.

2024-05-10 05:08 UTC, yorkie commented on tools/generate-dom-interfaces.js
> +}
```suggestion
};
```

This is a statement, it should be ended with a semi-colon.

2024-05-10 05:08 UTC, yorkie commented on tools/generate-dom-interfaces.js
> +}
Ditto

2024-05-10 05:16 UTC, yorkie commented on tools/generate-dom-interfaces.js
> +const buildExportGetInterfaceWrapper = (arg) => {
```suggestion
const buildGetInterfaceWrapperTypedDeclaration = (arg) => {
```

2024-05-10 07:21 UTC, yorkie commented on tools/generate-dom-interfaces.js
> +const buildInterfaceSetter = (arg) => {
```suggestion
const buildSetInterfaceStatement = (arg) => {
```

2024-05-10 09:03 UTC, yorkie commented on tools/generate-dom-interfaces.js
> +class DomInterfaceGenerator {
```suggestion
class DomInterfacesGenerator {
```

2024-05-10 09:05 UTC, neverbiasu commented on tools/generate-dom-interfaces.js
> +const generator = new DomInterfaceGenerator(moduleSpecifiers);
```suggestion
const generator = new DomInterfacesGenerator(moduleSpecifiers);
```

2024-05-10 09:05 UTC, yorkie commented on tools/generate-dom-interfaces.js
> +    if(isParallel) {
```suggestion
    if (isParallel) {
```

2024-05-10 09:07 UTC, yorkie commented on tools/generate-dom-interfaces.js
> +generator.writeToFile('interfaces.ts');
```suggestion
generator.writeToFile('src/living/interfaces.ts');
```

2024-05-10 09:07 UTC, yorkie commented on tools/generate-dom-interfaces.js
> +    const code = generate.default(t.program(interfacesModule)).code;
```suggestion
    return generate.default(t.program(interfacesModule)).code;
```

2024-05-10 09:37 UTC, yorkie approved these changes
Looks good to me if CI is green :)

2024-05-10 09:38 UTC, merged