feat: add type check for compatible
M-CreativeLab/jsar-dom pull request #4
Opened 2023-12-04 10:03 UTC by FeelyChau

2023-12-04 10:09 UTC, yorkie requested changes
整体上不错，提了几个建议。

2023-12-04 10:09 UTC, yorkie commented on src/living/nodes/Node.ts
> +  get parentNode(): ParentNode {
厉害！

2023-12-06 03:36 UTC, FeelyChau commented on src/type.utils.d.ts
> +export type Equal<X, Y> =
如果类型检查统一放在 living 下的话，这些类型可以直接放在一起，这个文件可以删除了。

2023-12-06 05:05 UTC, yorkie requested changes
1. 需要把 `as unknown` 去掉并使用正确的类型
2. 去掉 "type.utils.d.ts"

2023-12-06 05:05 UTC, yorkie commented on src/living/nodes/ChildNode.ts
> +    const parent = this.parentNode as unknown as NodeImpl;
我在本地试过，似乎不需要 `as unknown`，并且这里应该转成 `ParentNodeImpl` 就可以了。

2023-12-06 05:05 UTC, yorkie commented on src/living/nodes/ChildNode.ts
> +        parent._preInsert(node, viableNextSibling as unknown as NodeImpl);
同上，由于 nextSibling 是 ChildNode，因此 `as ChildNodeImpl` 即可，也不需要带 `as unknown`。

2023-12-06 14:24 UTC, FeelyChau commented on src/living/nodes/ChildNode.ts
> +      parent._preInsert(convertNodesIntoNode(this._ownerDocument, nodes), viableNextSibling as unknown as NodeImpl);
这里入参是 NodeImpl，原始类型是 ChildNode，无法直接转换。

2023-12-07 07:57 UTC, merged